
<p style="text-align: justify;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; PRIVACY POLICY</strong><br />Thanks for accessing and using www.love-push.com (the &ldquo;Website&rdquo;, or the<br />&ldquo;Service&rdquo;). In this Privacy Policy, we define how we collect, use and handle<br />your information when you submit them to us via our Services.</p>
<p style="text-align: justify;"><br /><strong>INFORMATION COLLECTED AND HOW WE USE SUCH INFORMATION</strong><br />We obtain and use the under listed information to provide, enhance and<br />protect our Services:</p>
<p style="text-align: justify;"><br /><strong>Your Personal Information:</strong> This service is a landing page for Love-Push,<br />where we may collect user&rsquo;s email addresses and other information as<br />requested.</p>
<p style="text-align: justify;"><br /><strong>Device information.</strong> We may also collect information from and about the<br />devices you use to access and use the Services. This may include details<br />such as IP address, the type of device and browser you use, the web page(s)<br />you visited before coming to our sites, and the unique device identifier. Your<br />tools (depending on their settings) may also transmit your location information<br />to the Services.</p>
<p style="text-align: justify;"><br /><strong>Cookies and other technologies.</strong> We may use technologies like cookies,<br />web beacons, etc. to provide, enhance, support, protect, and promote our<br />Services.<br />You can still also set your browser not to accept cookies, but this may limit<br />your ability to use the Services to the fullest.</p>
<p style="text-align: justify;"><br /><strong>Bases for processing your information:</strong> We collect and use the personal<br />information and all other information you submit to us as described above to<br />provide you the Services most securely and reliably. We also use your details<br />for or legitimate business needs. If we process your details for any other<br />reason not stated herein, we will seek your approval before the time; we willalso mandate our service providers to do likewise. For more information about<br />the bases for processing your details, please contact us.</p>
<p style="text-align: justify;"><br /><strong>INFORMATION SHARING</strong><br />Since we will not sell, rent or give your information to advertisers or other third<br />parties, we may decide to share your information as described below:</p>
<p style="text-align: justify;"><br /><strong>Our relevant service providers:</strong> Love-Push makes use of some trusted<br />service providers (for instance, for customer support) These service providers<br />will have access to your information for the singular purpose of performing<br />their duties to Love-Push in agreement with this Privacy Policy. We will remain<br />liable for the service provider&rsquo;s handling and management of any of the<br />information they access through our service. For the list of the service<br />providers which we use to process your personal information, please contact<br />us.</p>
<p style="text-align: justify;"><br /><strong>Law, Order and the general interest of the public:</strong> We may disclose or<br />share your information with a third party if we find out that such disclosure or<br />sharing is essential and necessary to:<br />i. to conform with any applicable rule, regulation or law;<br />ii. prevent death or serious personal injury;<br />iii. prevent illegal or unsanctioned transactions of Love-Push or our Users;<br />iv. secure Love-Push&rsquo;s intellectual property rights, interest or safety; or<br />v. carry out a task in the benefit of the general public.</p>
<p style="text-align: justify;"><br /><strong>DATA PROTECTION</strong><br />No data on the internet can be guaranteed as secure or safe. We strive to<br />safeguard information but are unable to ensure and cannot warrant the<br />security of any data which you share on the platform or transmit to us. You<br />understand that any information transmitted, submitted or posted on ourplatform is done at your own risk. Nevertheless, we will take reasonable steps<br />to ensure the security information on our Service.</p>
<p style="text-align: justify;"><br /><strong>CHANGES TO THIS PRIVACY POLICY</strong><br />If there is a chance that we are involved in a merger, acquisition,<br />reorganization, or sale of our assets, your information may be transferred as<br />part of the deal. We will promptly notify you via the email associated with your<br />account/profile of any such occurrence and outline your choices to you.<br />This Privacy Policy is subject to change frequently. We will post the most<br />recent version on our Site. If the version materially reduces your rights, we will<br />send a notification to you.</p>

